name: publish

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry update
      - name: Lint with pylint
        run: |
          poetry run pylint fastapi_redis_session
      - name: Check type
        run: |
          poetry run mypy fastapi_redis_session
      - name: Test with pytest
        run: |
          poetry run pytest
      - name: Publish Package to Pypi.org
        env:
          PYPI_TOKEN: ${{ secrets.FASTAPI_REDIS_SESSION_TOKEN }}
        run: |
          poetry config pypi-token.pypi $PYPI_TOKEN
          poetry publish --build
